// vue3/src/views/system/SecurityConfig.vue
<template>
  <div class="page-container">
    <div class="security-config-container">
      <h1>安全配置</h1>
      <el-form :model="formData" label-width="200px" class="security-form">
        <el-form-item label="允许多端登陆">
          <el-switch
            v-model="formData.allowMultipleLogin"
            :loading="loading"
            @change="(val) => handleUpdate('allowMultipleLogin', val)"
          />
          <div class="help-text">
            开启后一个账号可以多个设备同时登陆, 其他设备强制登陆后不会强制下线
          </div>
        </el-form-item>

        <el-form-item label="登录失败锁定">
          <el-switch
            v-model="formData.loginFailureLock"
            :loading="loading"
            @change="(val) => handleUpdate('loginFailureLock', val)"
          />
          <div class="help-text">
            开启后同个账号多次登陆失败后将会锁定账号无法继续登陆
          </div>
        </el-form-item>

        <el-form-item label="登录IP绑定">
          <el-switch
            v-model="formData.loginIpBind"
            :loading="loading"
            @change="(val) => handleUpdate('loginIpBind', val)"
          />
          <div class="help-text">
            开启后登陆凭证和IP进行绑定, 其他IP使用此登陆凭证则无法访问
          </div>
        </el-form-item>

        <el-form-item label="登录凭证自动续签">
          <el-switch
            v-model="formData.loginTokenAutoRenew"
            :loading="loading"
            @change="(val) => handleUpdate('loginTokenAutoRenew', val)"
          />
          <div class="help-text">
            登录凭证自动续签，当登录凭证过期后，自动续签，避免频繁登录
          </div>
        </el-form-item>

        <el-form-item label="凭证有效期(时)">
          <el-input
            v-model="formData.loginTokenExpire"
            type="number"
            @blur="handleNumberBlur('loginTokenExpire')"
          />
          <div class="help-text">
            设置登陆凭证有效期时长(时), 设置后下次登陆生效
          </div>
        </el-form-item>

        <el-form-item label="登录失败锁定阈值">
          <el-input
            v-model="formData.loginFailureLockThreshold"
            type="number"
            @blur="handleNumberBlur('loginFailureLockThreshold')"
          />
          <div class="help-text">
            设置登陆失败锁定阈值, 达到该值后账号会被锁定, 设置后下次登陆生效
          </div>
        </el-form-item>

        <el-form-item label="登录自动续签阈值">
          <el-input
            v-model="formData.loginTokenAutoRenewThreshold"
            type="number"
            @blur="handleNumberBlur('loginTokenAutoRenewThreshold')"
          />
          <div class="help-text">登陆凭证自动续签间隔(时)</div>
        </el-form-item>
      </el-form>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, onMounted } from "vue";
import { ElMessage } from "element-plus";
import { getSystemOption, updateOption } from "@/api/system";

const loading = ref(false);

const formData = reactive({
  allowMultipleLogin: false,
  loginFailureLock: false,
  loginIpBind: false,
  loginTokenAutoRenew: false,
  loginTokenExpire: null,
  loginFailureLockThreshold: null,
  loginTokenAutoRenewThreshold: null,
});

const fetchSecurityConfig = async () => {
  const res = await getSystemOption();
  Object.assign(formData, res.content || {});
};

const handleUpdate = async (optionKey, value) => {
  loading.value = true;
  try {
    await updateOption({ option: optionKey, value });
    ElMessage.success("配置更新成功");
  } finally {
    loading.value = false;
  }
};

const handleNumberBlur = (optionKey) => {
  const value = parseInt(formData[optionKey], 10);
  if (!isNaN(value)) {
    handleUpdate(optionKey, value);
  }
};

onMounted(() => {
  fetchSecurityConfig();
});
</script>

<style lang="less" scoped>
.security-config-container {
  padding: 24px;
  background: var(--cm-bg-card);
  border-radius: 4px;

  h1 {
    margin: 0 0 24px;
    font-size: 20px;
    font-weight: 500;
    color: rgba(0, 0, 0, 0.85);
  }

  .security-form {
    max-width: 720px;
  }

  .help-text {
    width: 100%;
    color: rgba(0, 0, 0, 0.45);
    font-size: 12px;
    line-height: 1.5;
    margin-top: 4px;
  }
}
</style>

// src/pages/system/security-config.tsx
// src/pages/system/SecurityConfigPage.tsx
import React, { useState, useEffect } from "react";
import { Form, Input, Space, Switch, message } from "antd";
import { useDispatch, useSelector } from "umi";
import styles from "./security-config.less";
import { SystemOption } from "@/models/system";

const SecurityConfigPage: React.FC = () => {
  const dispatch = useDispatch();
  const [form] = Form.useForm<SystemOption>();
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetchSecurityConfig();
  }, []);

  const fetchSecurityConfig = () => {
    dispatch({
      type: "system/getSystemOption",
      callback: (data: SystemOption) => {
        form.setFieldsValue(data);
      },
    });
  };

  const handleUpdate = (optionKey: keyof SystemOption, value: any) => {
    setLoading(true);
    dispatch({
      type: "system/updateOption",
      payload: {
        option: optionKey,
        value,
      },
      callback: () => {
        message.success("配置更新成功");
        setLoading(false);
      },
    });
  };

  return (
    <div className={styles["security-config-container"]}>
      <h1>安全配置</h1>
      <Form
        form={form}
        layout="horizontal"
        labelCol={{ span: 8 }}
        wrapperCol={{ span: 16 }}
      >
        <Form.Item
          label="允许多端登陆"
          name="allowMultipleLogin"
          valuePropName="checked"
          help="开启后一个账号可以多个设备同时登陆, 其他设备强制登陆后不会强制下线"
        >
          <Switch
            onChange={(checked) => {
              handleUpdate("allowMultipleLogin", checked);
            }}
          />
        </Form.Item>
        <Form.Item
          label="登录失败锁定"
          name="loginFailureLock"
          valuePropName="checked"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          help="开启后同个账号多次登陆失败后将会锁定账号无法继续登陆"
        >
          <Switch
            onChange={(checked) => {
              handleUpdate("loginFailureLock", checked);
            }}
          />
        </Form.Item>

        <Form.Item
          label="登录IP绑定"
          name="loginIpBind"
          valuePropName="checked"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 18 }}
          help="开启后登陆凭证和IP进行绑定, 其他IP使用此登陆凭证则无法访问"
        >
          <Switch
            onChange={(checked) => {
              handleUpdate("loginIpBind", checked);
            }}
          />
        </Form.Item>

        <Form.Item
          label="登录凭证自动续签"
          name="loginTokenAutoRenew"
          valuePropName="checked"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          help="登录凭证自动续签，当登录凭证过期后，自动续签，避免频繁登录"
        >
          <Switch
            onChange={(checked) => {
              handleUpdate("loginTokenAutoRenew", checked);
            }}
          />
        </Form.Item>

        <Form.Item
          label="凭证有效期(时)"
          name="loginTokenExpire"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          help="设置登陆凭证有效期时长(时), 设置后下次登陆生效"
        >
          <Input
            type="number"
            onBlur={(e) => {
              const value = parseInt(e.target.value, 10);
              if (!isNaN(value)) {
                handleUpdate("loginTokenExpire", value);
              }
            }}
          />
        </Form.Item>

        <Form.Item
          label="登录失败锁定阈值"
          name="loginFailureLockThreshold"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          help="设置登陆失败锁定阈值, 达到该值后账号会被锁定, 设置后下次登陆生效"
        >
          <Input
            type="number"
            onBlur={(e) => {
              const value = parseInt(e.target.value, 10);
              if (!isNaN(value)) {
                handleUpdate("loginFailureLockThreshold", value);
              }
            }}
          />
        </Form.Item>

        <Form.Item
          label="登录自动续签阈值"
          name="loginTokenAutoRenewThreshold"
          labelCol={{ span: 8 }}
          wrapperCol={{ span: 16 }}
          help="登陆凭证自动续签间隔(时)"
        >
          <Input
            type="number"
            onBlur={(e) => {
              const value = parseInt(e.target.value, 10);
              if (!isNaN(value)) {
                handleUpdate("loginTokenAutoRenewThreshold", value);
              }
            }}
          />
        </Form.Item>
      </Form>
    </div>
  );
};

export default SecurityConfigPage;
