// src/pages/system/system-log.tsx
import React, { useEffect, useState } from "react";
import {
  Button,
  Card,
  DatePicker,
  Form,
  Input,
  Popover,
  Select,
  Space,
  Table,
  Tag,
} from "antd";
import { connect, Dispatch } from "umi";
import { PageContainer } from "@ant-design/pro-components";
import { UserEventLogDTO } from "@/models/logs";
import moment from "moment";
import dayjs from "dayjs";
import { API } from "typings";

const { RangePicker } = DatePicker;
const { Option } = Select;

interface ClusterListProps {
  dispatch: Dispatch;
}

const LogPage: React.FC<ClusterListProps> = ({ dispatch }) => {
  const [pagination, setPagination] = useState({ pageNo: 1, pageSize: 10 });
  const [logs, setLogs] = useState<API.Page<UserEventLogDTO>>();
  const [eventClassifyList, setEventClassifyList] =
    useState<Record<string, string>>();
  const [eventTypeList, setEventTypeList] = useState<Record<string, string>>();
  const [filters, setFilters] = useState({
    userName: "",
    eventClassify: null,
    eventType: null,
    startDate: null,
    endDate: null,
  }); // 初始化筛选条件为空对象
  const [form] = Form.useForm();

  const queryLogs = () => {
    dispatch({
      type: "logs/queryLogs",
      payload: {
        ...filters,
        ...pagination,
      },
      callback: (res: API.Page<UserEventLogDTO>) => {
        setLogs(res);
      },
    });
  };

  const getEventClassify = () => {
    dispatch({
      type: "logs/getEventClassify",

      callback: (res: Record<string, string>) => {
        setEventClassifyList(res);
      },
    });
  };

  const getEventType = (classify: number) => {
    dispatch({
      type: "logs/getEventType",
      payload: { classify: classify },
      callback: (res: Record<string, string>) => {
        setEventTypeList(res);
      },
    });
  };

  useEffect(() => {
    getEventClassify();
  }, []);

  useEffect(() => {
    queryLogs();
  }, [filters, pagination]);

  const columns = [
    {
      title: "用户名",
      dataIndex: "userName",
      key: "userName",
    },
    {
      title: "事件分类",
      dataIndex: "eventClassifyName",
      key: "eventClassifyName",
    },
    {
      title: "事件类型",
      dataIndex: "eventTypeName",
      key: "eventTypeName",
    },
    {
      title: "日志时间",
      key: "gmtCreate",
      render: (text: string, record: UserEventLogDTO) => (
        <>{dayjs(record?.gmtCreate).format("YYYY-MM-DD HH:mm:ss")}</>
      ),
    },
    {
      title: "操作状态",
      dataIndex: "execResult",
      key: "execResult",
      render: (text: any, record: UserEventLogDTO) => {
        const tagColor = record.execResult === 1 ? "success" : "error";
        const statusText = record.execResult === 1 ? "成功" : "失败";
        return <Tag color={tagColor}>{statusText}</Tag>;
      },
    },
    {
      title: "操作",
      key: "actions",
      render: (text: any, record: UserEventLogDTO) => (
        <Popover
          content={<div dangerouslySetInnerHTML={{ __html: record.logInfo }} />}
          title="详细操作内容"
        >
          <Button type="link">查看</Button>
        </Popover>
      ),
    },
  ];

  const handlePaginationChange = (page: number, pageSize?: number) => {
    setPagination({ pageNo: page, pageSize: pageSize || 10 });
  };

  const onFinish = (values: any) => {
    handleFilterChange(values);
  };

  const handleFilterChange = (changedValues: any) => {
    const { timeRange, ...otherValues } = changedValues;
    if (timeRange && timeRange.length === 2) {
      const [startDate, endDate] = timeRange;
      setFilters((prevFilters) => ({
        ...prevFilters,
        startDate: startDate
          ? startDate.format("YYYY-MM-DD HH:mm:ss")
          : undefined,
        endDate: endDate ? endDate.format("YYYY-MM-DD HH:mm:ss") : undefined,
        ...otherValues,
      }));
    } else {
      setFilters((prevFilters) => ({
        ...prevFilters,
        startDate: undefined,
        endDate: undefined,
        ...otherValues,
      }));
    }
  };

  return (
    <PageContainer title="系统日志">
      <Card>
        <Space size="middle" direction="vertical" style={{ width: "100%" }}>
          <Form form={form} layout="inline" onFinish={onFinish}>
            <Form.Item name="userName" label="用户名">
              <Input placeholder="请输入用户名称" />
            </Form.Item>

            <Form.Item label="事件分类" name="eventClassify">
              <Select
                placeholder="请选择事件分类"
                onChange={(value) => {
                  setFilters((prevFilters) => ({
                    ...prevFilters,
                    eventClassify: value,
                    eventType: null, // 清空之前选择的事件类型
                  }));
                  getEventType(value); // 获取新的事件类型
                }}
                style={{ width: 150 }}
              >
                {Object.entries(eventClassifyList || {}).map(([key, value]) => (
                  <Option key={key} value={key}>
                    {value}
                  </Option>
                ))}
              </Select>
            </Form.Item>

            <Form.Item label="操作内容" name="eventType">
              <Select placeholder="请选择操作内容" style={{ width: 150 }}>
                {Object.entries(eventTypeList || {}).map(([key, value]) => (
                  <Option key={key} value={key}>
                    {value}
                  </Option>
                ))}
              </Select>
            </Form.Item>

            <Form.Item name="timeRange" label="时间范围">
              <RangePicker
                showTime
                placeholder={["开始时间", "结束时间"]}
                defaultValue={[
                  moment(dayjs().subtract(7, "day").toDate()),
                  moment(new Date()),
                ]}
              />
            </Form.Item>

            <Form.Item>
              <Button
                type="primary"
                htmlType="submit"
                style={{ marginRight: 8 }}
              >
                查询
              </Button>
              <Button htmlType="button" onClick={() => form.resetFields()}>
                重置
              </Button>
            </Form.Item>
          </Form>
          <Table
            columns={columns}
            dataSource={logs?.items}
            rowKey="id"
            pagination={{
              total: logs?.total,
              current: pagination.pageNo,
              pageSize: pagination.pageSize,
              onChange: handlePaginationChange,
            }}
          />
        </Space>
      </Card>
    </PageContainer>
  );
};
export default connect(({}) => ({}))(LogPage);

// vue2/src/views/system/SystemLog.vue
<template>
  <div class="page-container">
    <h2 class="page-title">系统日志</h2>
    <el-card>
      <el-form :inline="true" :model="searchForm" @submit.native.prevent="handleSearch">
        <el-form-item label="用户名">
          <el-input v-model="searchForm.userName" placeholder="请输入用户名称" clearable />
        </el-form-item>

        <el-form-item label="事件分类">
          <el-select
            v-model="searchForm.eventClassify"
            placeholder="请选择事件分类"
            style="width: 150px"
            clearable
            @change="handleClassifyChange"
          >
            <el-option
              v-for="(label, key) in eventClassifyList"
              :key="key"
              :label="label"
              :value="key"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="操作内容">
          <el-select
            v-model="searchForm.eventType"
            placeholder="请选择操作内容"
            style="width: 150px"
            clearable
          >
            <el-option
              v-for="(label, key) in eventTypeList"
              :key="key"
              :label="label"
              :value="key"
            />
          </el-select>
        </el-form-item>

        <el-form-item label="时间范围">
          <el-date-picker
            v-model="searchForm.timeRange"
            type="datetimerange"
            start-placeholder="开始时间"
            end-placeholder="结束时间"
            value-format="yyyy-MM-dd HH:mm:ss"
          />
        </el-form-item>

        <el-form-item>
          <el-button type="primary" native-type="submit">查询</el-button>
          <el-button @click="handleReset">重置</el-button>
        </el-form-item>
      </el-form>

      <el-table :data="logs" row-key="id" v-loading="loading">
        <el-table-column prop="userName" label="用户名" />
        <el-table-column prop="eventClassifyName" label="事件分类" />
        <el-table-column prop="eventTypeName" label="事件类型" />
        <el-table-column label="日志时间" width="170">
          <template slot-scope="{ row }">
            {{ formatTime(row.gmtCreate) }}
          </template>
        </el-table-column>
        <el-table-column label="操作状态" width="100">
          <template slot-scope="{ row }">
            <el-tag :type="row.execResult === 1 ? 'success' : 'danger'" size="small">
              {{ row.execResult === 1 ? "成功" : "失败" }}
            </el-tag>
          </template>
        </el-table-column>
        <el-table-column label="操作" width="100">
          <template slot-scope="{ row }">
            <el-popover placement="left" title="详细操作内容" trigger="click" width="400">
              <div v-html="row.logInfo"></div>
              <el-button slot="reference" type="text">查看</el-button>
            </el-popover>
          </template>
        </el-table-column>
      </el-table>

      <el-pagination
        class="pagination"
        layout="total, prev, pager, next, sizes"
        :total="total"
        :current-page="pagination.pageNo"
        :page-size="pagination.pageSize"
        @current-change="handlePageChange"
        @size-change="handleSizeChange"
      />
    </el-card>
  </div>
</template>

<script>
import dayjs from "dayjs";
import { queryLogs, getEventClassify, getEventType } from "@/api/logs";

export default {
  name: "SystemLog",
  data() {
    return {
      loading: false,
      pagination: { pageNo: 1, pageSize: 10 },
      searchForm: {
        userName: "",
        eventClassify: null,
        eventType: null,
        timeRange: [
          dayjs().subtract(7, "day").format("YYYY-MM-DD HH:mm:ss"),
          dayjs().format("YYYY-MM-DD HH:mm:ss"),
        ],
      },
      filters: {
        userName: "",
        eventClassify: null,
        eventType: null,
        startDate: null,
        endDate: null,
      },
      logs: [],
      total: 0,
      eventClassifyList: {},
      eventTypeList: {},
    };
  },
  created() {
    this.getEventClassifyList();
    this.queryLogList();
  },
  methods: {
    formatTime(time) {
      return time ? dayjs(time).format("YYYY-MM-DD HH:mm:ss") : "-";
    },
    async queryLogList() {
      this.loading = true;
      try {
        const res = await queryLogs({ ...this.filters, ...this.pagination });
        const page = res.content || {};
        this.logs = page.items || [];
        this.total = page.total || 0;
      } finally {
        this.loading = false;
      }
    },
    async getEventClassifyList() {
      const res = await getEventClassify();
      this.eventClassifyList = res.content || {};
    },
    async getEventTypeList(classify) {
      const res = await getEventType({ classify });
      this.eventTypeList = res.content || {};
    },
    handleClassifyChange(value) {
      // 切换分类时清空之前选择的事件类型并加载新的事件类型
      this.searchForm.eventType = null;
      this.eventTypeList = {};
      if (value) {
        this.getEventTypeList(value);
      }
    },
    handleSearch() {
      const { timeRange, userName, eventClassify, eventType } = this.searchForm;
      this.filters = {
        userName,
        eventClassify: eventClassify || null,
        eventType: eventType || null,
        startDate: timeRange && timeRange.length === 2 ? timeRange[0] : null,
        endDate: timeRange && timeRange.length === 2 ? timeRange[1] : null,
      };
      this.pagination.pageNo = 1;
      this.queryLogList();
    },
    handleReset() {
      this.searchForm = {
        userName: "",
        eventClassify: null,
        eventType: null,
        timeRange: null,
      };
      this.eventTypeList = {};
    },
    handlePageChange(page) {
      this.pagination.pageNo = page;
      this.queryLogList();
    },
    handleSizeChange(size) {
      this.pagination = { pageNo: 1, pageSize: size };
      this.queryLogList();
    },
  },
};
</script>

<style lang="less" scoped>
.page-title {
  margin: 0 0 16px;
  font-size: 20px;
  font-weight: 500;
}

.pagination {
  margin-top: 16px;
  text-align: right;
}

// 原 system-log.less
.title {
  background: rgb(242, 121, 135);
}
</style>
