// src/pages/system/system-analysis.tsx
import React, { useState, useEffect } from "react";
import styles from "./system-analysis.less";
import {
  Form,
  Input,
  Switch,
  Descriptions,
  Button,
  Tooltip,
  Modal,
  message,
} from "antd";
import { SYSTEM_CLEAR_TYPE, SYSTEM_OPTION_KEY } from "@/utils/index";
import { useDispatch, useSelector } from "umi";

const layout = {
  labelCol: { span: 5 },
  wrapperCol: { span: 17 },
};

// 类型定义
export interface AnalysisData {
  tempFileCount: number;
  tempFileSize: string;
  logFileCount: number;
  logFileSize: string;
  swapFileCount: number;
  swapFileSize: string;
  distVersionCount: number;
  distFileSize: string;
  repoVersionCount: number;
  repoVersionFileSize: string;
  screenFileCount: number;
  screenFileSize: string;

  fileCleanThreshold?: number;
  autoCleanFile?: boolean;
}

const SystemAnalysisPage: React.FC = () => {
  const dispatch = useDispatch();
  const [form] = Form.useForm();

  const [analysis, setAnalysis] = useState<AnalysisData>({
    tempFileCount: 0,
    tempFileSize: "0 B",
    logFileCount: 0,
    logFileSize: "0 B",
    swapFileCount: 0,
    swapFileSize: "0 B",
    distVersionCount: 0,
    distFileSize: "0 B",
    repoVersionCount: 0,
    repoVersionFileSize: "0 B",
    screenFileCount: 0,
    screenFileSize: "0 B",
    fileCleanThreshold: undefined,
    autoCleanFile: false,
  });

  const [visibleClean, setVisibleClean] = useState({
    tempFile: true,
    logFile: true,
    swapFile: true,
    distFile: true,
    repoFile: true,
    screenFile: true,
  });

  const [reAnalysisLoading, setReAnalysisLoading] = useState(false);
  const [fileCleanThreshold, setFileCleanThreshold] = useState<
    number | undefined
  >(undefined);
  const [fileCleanThresholdLoading, setFileCleanThresholdLoading] =
    useState(false);
  const [autoCleanFile, setAutoCleanFile] = useState(false);
  const [autoCleanFileLoading, setAutoCleanFileLoading] = useState(false);

  useEffect(() => {
    loadData();
  }, []);

  const loadData = () => {
    dispatch({
      type: "system/getSystemAnalysis",
      callback: (data: AnalysisData) => {
        setAnalysis(data);
        setFileCleanThreshold(data.fileCleanThreshold);
        setAutoCleanFile(!!data.autoCleanFile);
      },
    });
  };

  const saveCleanThreshold = () => {
    const threshold = parseInt(String(fileCleanThreshold), 10);
    if (threshold < 0) {
      message.warning("自动清理阈值不能小于0");
      return;
    }

    setFileCleanThresholdLoading(true);
    dispatch({
      type: "system/updateOption",
      payload: {
        option: SYSTEM_OPTION_KEY.FILE_CLEAN_THRESHOLD.value,
        value: threshold,
      },
      callback: (success: boolean) => {
        message.success("已保存");
        setFileCleanThresholdLoading(false);
      },
      onError: (success: boolean) => {
        message.error("保存失败");
        setFileCleanThresholdLoading(false);
      },
    });
  };

  const changeAutoClean = (checked: boolean) => {
    setAutoCleanFileLoading(true);
    dispatch({
      type: "system/updateOption",
      payload: {
        option: SYSTEM_OPTION_KEY.ENABLE_AUTO_CLEAN_FILE.value,
        value: checked,
      },
      callback: (success: boolean) => {
        setAutoCleanFile(checked);
        message.success("已保存");
        setAutoCleanFileLoading(false);
      },
      onError: () => {
        message.error("保存失败");
        setAutoCleanFileLoading(false);
      },
    });
  };

  const clear = async (type: any) => {
    Modal.confirm({
      title: "确认清理",
      content:
        "确认后会清理超过清理阈值的所有文件, 请先确认数据是否已备份, 清理后数据无法回滚!",
      okText: "确认",
      okType: "danger",
      cancelText: "取消",
      onOk: () => {
        setVisibleClean((prev) => ({ ...prev, [type.key]: false }));
        const pending = message.loading(`正在提交 ${type.label} 清理任务...`);
        dispatch({
          type: "system/cleanFiles",
          payload: {
            cleanType: type.value,
          },
          callback: () => {
            pending();
            message.success(
              `正在清理 ${type.label}, 清理完成后需要手动点击重新分析`
            );
          },
          onError: () => {
            pending();
            setVisibleClean((prev) => ({ ...prev, [type.key]: true }));
          },
        });
      },
    });
  };

  const reAnalysis = () => {
    setReAnalysisLoading(true);
    dispatch({
      type: "system/reAnalyze",
      callback: (data: AnalysisData) => {
        setReAnalysisLoading(false);
        for (const key in visibleClean) {
          setVisibleClean((prev) => ({ ...prev, [key]: true }));
        }
        setAnalysis(data);
      },
      onError: () => {
        message.error("重新分析失败");
        setReAnalysisLoading(false);
      },
    });
  };

  return (
    <div className={styles["system-analysis-container"]}>
      {/* 清理配置 */}
      <div className={styles["system-clean-container"]}>
        <div className={styles["system-clean-title"]}>清理配置</div>
        <div className={styles["system-clean-form-wrapper"]}>
          <Form form={form} {...layout}>
            <Form.Item label="清理阈值(天)">
              <Input
                className={styles["clean-threshold-input"]}
                value={fileCleanThreshold}
                onChange={(e) =>
                  setFileCleanThreshold(parseInt(e.target.value, 10))
                }
                disabled={fileCleanThresholdLoading}
              />
              <Button
                type="primary"
                loading={fileCleanThresholdLoading}
                onClick={saveCleanThreshold}
                style={{ marginLeft: 8 }}
              >
                保存
              </Button>
              <div className={styles.extra}>
                设置后清理文件时会删除当前时间减当前值之前修改的所有文件,
                如果设置为0则全部清理
              </div>
            </Form.Item>
            <Form.Item label="自动清理">
              <Switch
                checked={autoCleanFile}
                loading={autoCleanFileLoading}
                onChange={changeAutoClean}
              />
              <div className={styles.extra}>
                开启后每天1:30会自动清理超过所配置阈值的文件
              </div>
            </Form.Item>
          </Form>
        </div>
      </div>

      {/* 系统统计分析 */}
      <div className={styles["system-analysis-descriptions"]}>
        <div className={styles["system-analysis-title"]}>系统统计分析</div>
        <div className={styles["analysis-items"]}>
          <div className={styles["analysis-item"]}>
            <span className={styles["analysis-label"]}>临时文件：</span>
            <span className={styles["analysis-count"]}>
              {analysis.tempFileCount} 个
            </span>
            <span className={styles["analysis-size"]}>
              {analysis.tempFileSize}
            </span>
          </div>
          <div className={styles["analysis-item"]}>
            <span className={styles["analysis-label"]}>日志文件：</span>
            <span className={styles["analysis-count"]}>
              {analysis.logFileCount} 个
            </span>
            <span className={styles["analysis-size"]}>
              {analysis.logFileSize}
            </span>
          </div>
          <div className={styles["analysis-item"]}>
            <span className={styles["analysis-label"]}>交换区文件：</span>
            <span className={styles["analysis-count"]}>
              {analysis.swapFileCount} 个
            </span>
            <span className={styles["analysis-size"]}>
              {analysis.swapFileSize}
            </span>
          </div>
          <div className={styles["analysis-item"]}>
            <span className={styles["analysis-label"]}>构建产物：</span>
            <span className={styles["analysis-count"]}>
              {analysis.distVersionCount} 个
            </span>
            <span className={styles["analysis-size"]}>
              {analysis.distFileSize}
            </span>
          </div>
          <div className={styles["analysis-item"]}>
            <span className={styles["analysis-label"]}>录屏文件：</span>
            <span className={styles["analysis-count"]}>
              {analysis.screenFileCount} 个
            </span>
            <span className={styles["analysis-size"]}>
              {analysis.screenFileSize}
            </span>
          </div>
        </div>
      </div>

      {/* 操作按钮 */}
      <div className={styles["system-analysis-handler-container"]}>
        <Button onClick={reAnalysis} className={styles["re-analysis-button"]}>
          重新分析
        </Button>
      </div>
    </div>
  );
};

export default SystemAnalysisPage;

// vue2/src/views/system/SystemAnalysis.vue
<template>
  <div class="page-container">
    <div class="system-analysis-container">
      <!-- 清理配置 -->
      <div class="system-clean-container">
        <div class="system-clean-title">清理配置</div>
        <div class="system-clean-form-wrapper">
          <el-form label-width="120px">
            <el-form-item label="清理阈值(天)">
              <el-input
                v-model="fileCleanThreshold"
                class="clean-threshold-input"
                :disabled="fileCleanThresholdLoading"
              />
              <el-button
                type="primary"
                :loading="fileCleanThresholdLoading"
                style="margin-left: 8px"
                @click="saveCleanThreshold"
              >
                保存
              </el-button>
              <div class="extra">
                设置后清理文件时会删除当前时间减当前值之前修改的所有文件,
                如果设置为0则全部清理
              </div>
            </el-form-item>
            <el-form-item label="自动清理">
              <el-switch
                v-model="autoCleanFile"
                :disabled="autoCleanFileLoading"
                @change="changeAutoClean"
              />
              <div class="extra">开启后每天1:30会自动清理超过所配置阈值的文件</div>
            </el-form-item>
          </el-form>
        </div>
      </div>

      <!-- 系统统计分析 -->
      <div class="system-analysis-descriptions">
        <div class="system-analysis-title">系统统计分析</div>
        <div class="analysis-items">
          <div v-for="item in analysisItems" :key="item.key" class="analysis-item">
            <span class="analysis-label">{{ item.label }}：</span>
            <span class="analysis-count">{{ analysis[item.countField] }} 个</span>
            <span class="analysis-size">{{ analysis[item.sizeField] }}</span>
            <el-button
              v-if="visibleClean[item.key]"
              type="text"
              class="clean-button"
              @click="clear(item.clearType)"
            >
              清理
            </el-button>
          </div>
        </div>
      </div>

      <!-- 操作按钮 -->
      <div class="system-analysis-handler-container">
        <el-button
          class="re-analysis-button"
          :loading="reAnalysisLoading"
          @click="reAnalysis"
        >
          重新分析
        </el-button>
      </div>
    </div>
  </div>
</template>

<script>
import {
  getSystemAnalysis,
  updateOption,
  cleanSystemFile,
  reAnalysisSystem,
} from "@/api/system";

// 系统配置项 (原 src/utils/index SYSTEM_OPTION_KEY)
const SYSTEM_OPTION_KEY = {
  FILE_CLEAN_THRESHOLD: { key: "fileCleanThreshold", value: 10 },
  ENABLE_AUTO_CLEAN_FILE: { key: "autoCleanFile", value: 20 },
};

// 系统清理类型 (原 src/utils/index SYSTEM_CLEAR_TYPE)
const SYSTEM_CLEAR_TYPE = {
  TEMP_FILE: { key: "tempFile", value: 10, label: "临时文件" },
  LOG_FILE: { key: "logFile", value: 20, label: "日志文件" },
  SWAP_FILE: { key: "swapFile", value: 30, label: "交换区文件" },
  DIST_FILE: { key: "distFile", value: 40, label: "旧版本构建产物" },
  REPO_FILE: { key: "repoFile", value: 50, label: "旧版本应用仓库" },
  SCREEN_FILE: { key: "screenFile", value: 60, label: "录屏文件" },
};

export default {
  name: "SystemAnalysis",
  data() {
    return {
      analysis: {
        tempFileCount: 0,
        tempFileSize: "0 B",
        logFileCount: 0,
        logFileSize: "0 B",
        swapFileCount: 0,
        swapFileSize: "0 B",
        distVersionCount: 0,
        distFileSize: "0 B",
        repoVersionCount: 0,
        repoVersionFileSize: "0 B",
        screenFileCount: 0,
        screenFileSize: "0 B",
      },
      analysisItems: [
        {
          key: "tempFile",
          label: "临时文件",
          countField: "tempFileCount",
          sizeField: "tempFileSize",
          clearType: SYSTEM_CLEAR_TYPE.TEMP_FILE,
        },
        {
          key: "logFile",
          label: "日志文件",
          countField: "logFileCount",
          sizeField: "logFileSize",
          clearType: SYSTEM_CLEAR_TYPE.LOG_FILE,
        },
        {
          key: "swapFile",
          label: "交换区文件",
          countField: "swapFileCount",
          sizeField: "swapFileSize",
          clearType: SYSTEM_CLEAR_TYPE.SWAP_FILE,
        },
        {
          key: "distFile",
          label: "构建产物",
          countField: "distVersionCount",
          sizeField: "distFileSize",
          clearType: SYSTEM_CLEAR_TYPE.DIST_FILE,
        },
        {
          key: "screenFile",
          label: "录屏文件",
          countField: "screenFileCount",
          sizeField: "screenFileSize",
          clearType: SYSTEM_CLEAR_TYPE.SCREEN_FILE,
        },
      ],
      visibleClean: {
        tempFile: true,
        logFile: true,
        swapFile: true,
        distFile: true,
        repoFile: true,
        screenFile: true,
      },
      reAnalysisLoading: false,
      fileCleanThreshold: undefined,
      fileCleanThresholdLoading: false,
      autoCleanFile: false,
      autoCleanFileLoading: false,
    };
  },
  created() {
    this.loadData();
  },
  methods: {
    async loadData() {
      const res = await getSystemAnalysis();
      const data = res.content || {};
      this.analysis = data;
      this.fileCleanThreshold = data.fileCleanThreshold;
      this.autoCleanFile = !!data.autoCleanFile;
    },
    async saveCleanThreshold() {
      const threshold = parseInt(String(this.fileCleanThreshold), 10);
      if (threshold < 0) {
        this.$message.warning("自动清理阈值不能小于0");
        return;
      }
      this.fileCleanThresholdLoading = true;
      try {
        await updateOption({
          option: SYSTEM_OPTION_KEY.FILE_CLEAN_THRESHOLD.value,
          value: threshold,
        });
        this.$message.success("已保存");
      } catch (e) {
        this.$message.error("保存失败");
      } finally {
        this.fileCleanThresholdLoading = false;
      }
    },
    async changeAutoClean(checked) {
      this.autoCleanFileLoading = true;
      try {
        await updateOption({
          option: SYSTEM_OPTION_KEY.ENABLE_AUTO_CLEAN_FILE.value,
          value: checked,
        });
        this.autoCleanFile = checked;
        this.$message.success("已保存");
      } catch (e) {
        this.autoCleanFile = !checked;
        this.$message.error("保存失败");
      } finally {
        this.autoCleanFileLoading = false;
      }
    },
    clear(type) {
      this.$confirm(
        "确认后会清理超过清理阈值的所有文件, 请先确认数据是否已备份, 清理后数据无法回滚!",
        "确认清理",
        {
          confirmButtonText: "确认",
          cancelButtonText: "取消",
          confirmButtonClass: "el-button--danger",
          type: "warning",
        }
      )
        .then(async () => {
          this.$set(this.visibleClean, type.key, false);
          const pending = this.$message({
            message: `正在提交 ${type.label} 清理任务...`,
            duration: 0,
          });
          try {
            await cleanSystemFile({ cleanType: type.value });
            pending.close();
            this.$message.success(
              `正在清理 ${type.label}, 清理完成后需要手动点击重新分析`
            );
          } catch (e) {
            pending.close();
            this.$set(this.visibleClean, type.key, true);
          }
        })
        .catch(() => {});
    },
    async reAnalysis() {
      this.reAnalysisLoading = true;
      try {
        await reAnalysisSystem();
        Object.keys(this.visibleClean).forEach((key) => {
          this.$set(this.visibleClean, key, true);
        });
        await this.loadData();
      } catch (e) {
        this.$message.error("重新分析失败");
      } finally {
        this.reAnalysisLoading = false;
      }
    },
  },
};
</script>

<style lang="less" scoped>
.system-analysis-container {
  padding: 24px;
  background: #fff;
  border-radius: 4px;

  .system-clean-container {
    margin-bottom: 24px;

    .system-clean-title {
      font-size: 16px;
      font-weight: 500;
      color: rgba(0, 0, 0, 0.85);
      margin-bottom: 16px;
    }

    .system-clean-form-wrapper {
      .clean-threshold-input {
        width: 200px;
      }

      .extra {
        color: rgba(0, 0, 0, 0.45);
        margin-top: 8px;
      }
    }
  }

  .system-analysis-descriptions {
    .system-analysis-title {
      font-size: 16px;
      font-weight: 500;
      color: rgba(0, 0, 0, 0.85);
      margin: 24px 0 16px;
    }

    .analysis-items {
      .analysis-item {
        display: flex;
        align-items: center;
        margin-bottom: 16px;

        .analysis-label {
          width: 120px;
          text-align: right;
          margin-right: 16px;
          color: rgba(0, 0, 0, 0.65);
        }

        .analysis-count,
        .analysis-size {
          font-size: 14px;
          color: rgba(0, 0, 0, 0.65);
        }

        .analysis-size {
          margin-left: 16px;
          color: #1890ff;
        }

        .clean-button {
          margin-left: 16px;
          padding: 0;
        }
      }
    }
  }

  .system-analysis-handler-container {
    margin-top: 24px;
    text-align: left;

    .re-analysis-button {
      padding: 0 16px;
      height: 32px;
      line-height: 32px;
      font-size: 14px;
    }
  }
}
</style>
